# 1. Set 1835 as the default game variant (Key used in getDefaultGame())
default_game=1835

# 2. Set default player names
player.name.1=Stefan
player.name.2=Rainer
player.name.3=Bjoern
player.name.4=Christian

# 3. Set desired default game options (the 'ticks')
# These remain the same, as they are likely checked by other classes.
map.route.highlight=true
orPanel.revenue.suggest=true
orPanel.showAllCompanies=always
orPanel.showSpinner=no
ai.save.state.on.move=true